export const AUDIT_ACTIONS = Object.freeze({
  APPOINTMENT_CREATED: "APPOINTMENT_CREATED",
  APPOINTMENT_STARTED: "APPOINTMENT_STARTED",
  APPOINTMENT_COMPLETED: "APPOINTMENT_COMPLETED",

  HEALTH_RECORD_CREATED: "HEALTH_RECORD_CREATED",
  HEALTH_RECORD_FINALIZED: "HEALTH_RECORD_FINALIZED",

  PRESCRIPTION_CREATED: "PRESCRIPTION_CREATED",
  PRESCRIPTION_UPDATED: "PRESCRIPTION_UPDATED",

  TEST_ORDERED: "TEST_ORDERED",
  TEST_REPORT_UPLOADED: "TEST_REPORT_UPLOADED",
});
