
export const ROLES = Object.freeze({
  SUPER_ADMIN: "SUPER_ADMIN",
  HOSPITAL_ADMIN: "HOSPITAL_ADMIN",
  DOCTOR: "DOCTOR",
  RECEPTION: "RECEPTION",
  LAB_ADMIN: "LAB_ADMIN",
  PATIENT: "PATIENT",
});
